# --------------------------------------------------------------------------------------------------
# -------------------------------------- Weatherlight :: Nodes -------------------------------------
# --------------------------------------------------------------------------------------------------
from . Color import Color
from . Colors import Colors
from . Identity import Identity
from . Subtype import Subtype
from . Subtypes import Subtypes
from . Supertype import Supertype
from . Supertypes import Supertypes
from . Type import Type
from . Types import Types

from . Color import Black
from . Color import Blue
from . Color import Colorless
from . Color import Green
from . Color import Red
from . Color import White

from . Subtype import Blood
from . Subtype import Clue
from . Subtype import Equipment
from . Subtype import Food
from . Subtype import Fortification
from . Subtype import Gold
from . Subtype import Map
from . Subtype import Powerstone
from . Subtype import Treasure
from . Subtype import Vehicle
from . Subtype import Siege
from . Subtype import Advisor
from . Subtype import Aetherborn
from . Subtype import Alien
from . Subtype import Ally
from . Subtype import Angel
from . Subtype import Antelope
from . Subtype import Ape
from . Subtype import Archer
from . Subtype import Archon
from . Subtype import Armadillo
from . Subtype import Army
from . Subtype import Artificer
from . Subtype import Assassin
from . Subtype import AssemblyWorker
from . Subtype import Atog
from . Subtype import Aurochs
from . Subtype import Avatar
from . Subtype import Azra
from . Subtype import Badger
from . Subtype import Balloon
from . Subtype import Barbarian
from . Subtype import Bard
from . Subtype import Basilisk
from . Subtype import Bat
from . Subtype import Bear
from . Subtype import Beast
from . Subtype import Beeble
from . Subtype import Beholder
from . Subtype import Berserker
from . Subtype import Bird
from . Subtype import Blinkmoth
from . Subtype import Boar
from . Subtype import Bringer
from . Subtype import Brushwagg
from . Subtype import Camarid
from . Subtype import Camel
from . Subtype import Caribou
from . Subtype import Carrier
from . Subtype import Cat
from . Subtype import Centaur
from . Subtype import Cephalid
from . Subtype import Chimera
from . Subtype import Citizen
from . Subtype import Cleric
from . Subtype import Cockatrice
from . Subtype import Construct
from . Subtype import Coward
from . Subtype import Crab
from . Subtype import Crocodile
from . Subtype import Cyclops
from . Subtype import Dauthi
from . Subtype import Demigod
from . Subtype import Demon
from . Subtype import Deserter
from . Subtype import Devil
from . Subtype import Dinosaur
from . Subtype import Djinn
from . Subtype import Dog
from . Subtype import Dragon
from . Subtype import Drake
from . Subtype import Dreadnought
from . Subtype import Drone
from . Subtype import Druid
from . Subtype import Dryad
from . Subtype import Dwarf
from . Subtype import Efreet
from . Subtype import Egg
from . Subtype import Elder
from . Subtype import Eldrazi
from . Subtype import Elemental
from . Subtype import Elephant
from . Subtype import Elf
from . Subtype import Elk
from . Subtype import Eye
from . Subtype import Faerie
from . Subtype import Ferret
from . Subtype import Fish
from . Subtype import Flagbearer
from . Subtype import Fox
from . Subtype import Fractal
from . Subtype import Frog
from . Subtype import Fungus
from . Subtype import Gargoyle
from . Subtype import Germ
from . Subtype import Giant
from . Subtype import Gnoll
from . Subtype import Gnome
from . Subtype import Goat
from . Subtype import Goblin
from . Subtype import God
from . Subtype import Golem
from . Subtype import Gorgon
from . Subtype import Graveborn
from . Subtype import Gremlin
from . Subtype import Griffin
from . Subtype import Hag
from . Subtype import Harpy
from . Subtype import Hellion
from . Subtype import Hippo
from . Subtype import Hippogriff
from . Subtype import Homarid
from . Subtype import Homunculus
from . Subtype import Horror
from . Subtype import Horse
from . Subtype import Human
from . Subtype import Hydra
from . Subtype import Hyena
from . Subtype import Illusion
from . Subtype import Imp
from . Subtype import Incarnation
from . Subtype import Inkling
from . Subtype import Insect
from . Subtype import Jackal
from . Subtype import Jellyfish
from . Subtype import Juggernaut
from . Subtype import Kavu
from . Subtype import Kirin
from . Subtype import Kithkin
from . Subtype import Knight
from . Subtype import Kobold
from . Subtype import Kor
from . Subtype import Kraken
from . Subtype import Lamia
from . Subtype import Lammasu
from . Subtype import Leech
from . Subtype import Leviathan
from . Subtype import Lhurgoyf
from . Subtype import Licid
from . Subtype import Lizard
from . Subtype import Manticore
from . Subtype import Masticore
from . Subtype import Mercenary
from . Subtype import Merfolk
from . Subtype import Metathran
from . Subtype import Minion
from . Subtype import Minotaur
from . Subtype import Mite
from . Subtype import Mole
from . Subtype import Mongoose
from . Subtype import Monk
from . Subtype import Monkey
from . Subtype import Moonfolk
from . Subtype import Mount
from . Subtype import Mouse
from . Subtype import Mutant
from . Subtype import Myr
from . Subtype import Mystic
from . Subtype import Naga
from . Subtype import Nautilus
from . Subtype import Nephilim
from . Subtype import Nightmare
from . Subtype import Nightstalker
from . Subtype import Ninja
from . Subtype import Noble
from . Subtype import Noggle
from . Subtype import Nomad
from . Subtype import Nymph
from . Subtype import Octopus
from . Subtype import Ogre
from . Subtype import Ooze
from . Subtype import Orb
from . Subtype import Orc
from . Subtype import Orgg
from . Subtype import Otter
from . Subtype import Ouphe
from . Subtype import Ox
from . Subtype import Oyster
from . Subtype import Pangolin
from . Subtype import Peasant
from . Subtype import Pegasus
from . Subtype import Pentavite
from . Subtype import Pest
from . Subtype import Phelddagrif
from . Subtype import Phoenix
from . Subtype import Phyrexian
from . Subtype import Pilot
from . Subtype import Pincher
from . Subtype import Pirate
from . Subtype import Plant
from . Subtype import Praetor
from . Subtype import Primordial
from . Subtype import Prism
from . Subtype import Processor
from . Subtype import Rabbit
from . Subtype import Raccoon
from . Subtype import Rat
from . Subtype import Rebel
from . Subtype import Reflection
from . Subtype import Rhino
from . Subtype import Rigger
from . Subtype import Rogue
from . Subtype import Sable
from . Subtype import Salamander
from . Subtype import Samurai
from . Subtype import Sand
from . Subtype import Saproling
from . Subtype import Satyr
from . Subtype import Scarecrow
from . Subtype import Scientist
from . Subtype import Scion
from . Subtype import Scorpion
from . Subtype import Scout
from . Subtype import Serf
from . Subtype import Serpent
from . Subtype import Servo
from . Subtype import Shade
from . Subtype import Shaman
from . Subtype import Shapeshifter
from . Subtype import Shark
from . Subtype import Sheep
from . Subtype import Siren
from . Subtype import Skeleton
from . Subtype import Slith
from . Subtype import Sliver
from . Subtype import Slug
from . Subtype import Snake
from . Subtype import Soldier
from . Subtype import Soltari
from . Subtype import Spawn
from . Subtype import Specter
from . Subtype import Spellshaper
from . Subtype import Sphinx
from . Subtype import Spider
from . Subtype import Spike
from . Subtype import Spirit
from . Subtype import Splinter
from . Subtype import Sponge
from . Subtype import Squid
from . Subtype import Squirrel
from . Subtype import Starfish
from . Subtype import Surrakar
from . Subtype import Survivor
from . Subtype import Tentacle
from . Subtype import Tetravite
from . Subtype import Thalakos
from . Subtype import Thopter
from . Subtype import Thrull
from . Subtype import Tiefling
from . Subtype import Treefolk
from . Subtype import Trilobite
from . Subtype import Triskelavite
from . Subtype import Troll
from . Subtype import Turtle
from . Subtype import Tyranid
from . Subtype import Unicorn
from . Subtype import Vampire
from . Subtype import Vedalken
from . Subtype import Viashino
from . Subtype import Voliver
from . Subtype import Wall
from . Subtype import Warlock
from . Subtype import Warrior
from . Subtype import Weird
from . Subtype import Werewolf
from . Subtype import Whale
from . Subtype import Wizard
from . Subtype import Wolf
from . Subtype import Wolverine
from . Subtype import Wombat
from . Subtype import Worm
from . Subtype import Wraith
from . Subtype import Wurm
from . Subtype import Yeti
from . Subtype import Zombie
from . Subtype import Zubera
from . Subtype import Aura
from . Subtype import Background
from . Subtype import Cartouche
from . Subtype import Function
from . Subtype import Curse
from . Subtype import Rune
from . Subtype import Saga
from . Subtype import Shrine
from . Subtype import Role
from . Subtype import Desert
from . Subtype import Forest
from . Subtype import Gate
from . Subtype import Island
from . Subtype import Lair
from . Subtype import Locus
from . Subtype import Mine
from . Subtype import Mountain
from . Subtype import Plains
from . Subtype import PowerPlant
from . Subtype import Sphere
from . Subtype import Swamp
from . Subtype import Tower
from . Subtype import Urzas
from . Subtype import Ajani
from . Subtype import Angrath
from . Subtype import Arlinn
from . Subtype import Ashiok
from . Subtype import Basri
from . Subtype import Bolas
from . Subtype import Calix
from . Subtype import Chandra
from . Subtype import Dack
from . Subtype import Dakkon
from . Subtype import Davriel
from . Subtype import Domri
from . Subtype import Dovin
from . Subtype import Elspeth
from . Subtype import Estrid
from . Subtype import Freyalise
from . Subtype import Garruk
from . Subtype import Gideon
from . Subtype import Hualti
from . Subtype import Jace
from . Subtype import Jared
from . Subtype import Jaya
from . Subtype import Jeska
from . Subtype import Kaito
from . Subtype import Karn
from . Subtype import Kasmina
from . Subtype import Kaya
from . Subtype import Kiora
from . Subtype import Koth
from . Subtype import Liliana
from . Subtype import Lukka
from . Subtype import Narset
from . Subtype import Nahiri
from . Subtype import Niko
from . Subtype import Nissa
from . Subtype import Obi
from . Subtype import Ob
from . Subtype import Oko
from . Subtype import Ral
from . Subtype import Rowan
from . Subtype import Saheeli
from . Subtype import Samut
from . Subtype import Sarkhan
from . Subtype import Serra
from . Subtype import Sorin
from . Subtype import Tamiyo
from . Subtype import Teferi
from . Subtype import Teyo
from . Subtype import Tezzeret
from . Subtype import Tibalt
from . Subtype import Tyvar
from . Subtype import Ugin
from . Subtype import Venser
from . Subtype import Vivien
from . Subtype import Vraska
from . Subtype import Will
from . Subtype import Windgrace
from . Subtype import Wrenn
from . Subtype import Xenagos
from . Subtype import Yanggu
from . Subtype import Yanling
from . Subtype import Adventure
from . Subtype import Arcane
from . Subtype import Lesson
from . Subtype import Trap

from . Supertype import Basic
from . Supertype import Legendary
from . Supertype import Snow
from . Supertype import World

from . Type import Artifact
from . Type import Battle
from . Type import Creature
from . Type import Dungeon
from . Type import Enchantment
from . Type import Instant
from . Type import Kindred
from . Type import Land
from . Type import Planeswalker
from . Type import Sorcery