# --------------------------------------------------------------------------------------------------
# ------------------------ Weatherlight :: Generators :: Identity Generator ------------------------
# --------------------------------------------------------------------------------------------------
from .. Autoencoder import Autoencoder
from .. Nodes import *
from .. Slots import *
from .. Autoencoder import Type

import random
import itertools
import operator
import toolz


# --------------------------------------------------------------------------------------------------
# ------------------------------ Generator :: Identity Graph Generator -----------------------------
# --------------------------------------------------------------------------------------------------
class Generator(object):

	# ------------------------------------------------------------------------------------------
	# ----------------------------- Method :: Fabricate an Identity ----------------------------
	# ------------------------------------------------------------------------------------------
	@staticmethod
	def fabricate() -> Identity:

		supertypes = random.sample([
			Basic,
			Legendary,
			Snow,
			World,
		], random.randint(0, 4))

		types = random.sample([
			Artifact,
			Battle,
			Creature,
			Dungeon,
			Enchantment,
			Instant,
			Kindred,
			Land,
			Planeswalker,
			Sorcery,
		], random.randint(0, 10))

		subtypes = random.sample([
			Blood,
			Clue,
			Equipment,
			Food,
			Fortification,
			Gold,
			Map,
			Powerstone,
			Treasure,
			Vehicle,
			Siege,
			Advisor,
			Aetherborn,
			Alien,
			Ally,
			Angel,
			Antelope,
			Ape,
			Archer,
			Archon,
			Armadillo,
			Army,
			Artificer,
			Assassin,
			AssemblyWorker,
			Atog,
			Aurochs,
			Avatar,
			Azra,
			Badger,
			Balloon,
			Barbarian,
			Bard,
			Basilisk,
			Bat,
			Bear,
			Beast,
			Beeble,
			Beholder,
			Berserker,
			Bird,
			Blinkmoth,
			Boar,
			Bringer,
			Brushwagg,
			Camarid,
			Camel,
			Caribou,
			Carrier,
			Cat,
			Centaur,
			Cephalid,
			Chimera,
			Citizen,
			Cleric,
			Cockatrice,
			Construct,
			Coward,
			Crab,
			Crocodile,
			Cyclops,
			Dauthi,
			Demigod,
			Demon,
			Deserter,
			Devil,
			Dinosaur,
			Djinn,
			Dog,
			Dragon,
			Drake,
			Dreadnought,
			Drone,
			Druid,
			Dryad,
			Dwarf,
			Efreet,
			Egg,
			Elder,
			Eldrazi,
			Elemental,
			Elephant,
			Elf,
			Elk,
			Eye,
			Faerie,
			Ferret,
			Fish,
			Flagbearer,
			Fox,
			Fractal,
			Frog,
			Fungus,
			Gargoyle,
			Germ,
			Giant,
			Gnoll,
			Gnome,
			Goat,
			Goblin,
			God,
			Golem,
			Gorgon,
			Graveborn,
			Gremlin,
			Griffin,
			Hag,
			Harpy,
			Hellion,
			Hippo,
			Hippogriff,
			Homarid,
			Homunculus,
			Horror,
			Horse,
			Human,
			Hydra,
			Hyena,
			Illusion,
			Imp,
			Incarnation,
			Inkling,
			Insect,
			Jackal,
			Jellyfish,
			Juggernaut,
			Kavu,
			Kirin,
			Kithkin,
			Knight,
			Kobold,
			Kor,
			Kraken,
			Lamia,
			Lammasu,
			Leech,
			Leviathan,
			Lhurgoyf,
			Licid,
			Lizard,
			Manticore,
			Masticore,
			Mercenary,
			Merfolk,
			Metathran,
			Minion,
			Minotaur,
			Mite,
			Mole,
			Mongoose,
			Monk,
			Monkey,
			Moonfolk,
			Mount,
			Mouse,
			Mutant,
			Myr,
			Mystic,
			Naga,
			Nautilus,
			Nephilim,
			Nightmare,
			Nightstalker,
			Ninja,
			Noble,
			Noggle,
			Nomad,
			Nymph,
			Octopus,
			Ogre,
			Ooze,
			Orb,
			Orc,
			Orgg,
			Otter,
			Ouphe,
			Ox,
			Oyster,
			Pangolin,
			Peasant,
			Pegasus,
			Pentavite,
			Pest,
			Phelddagrif,
			Phoenix,
			Phyrexian,
			Pilot,
			Pincher,
			Pirate,
			Plant,
			Praetor,
			Primordial,
			Prism,
			Processor,
			Rabbit,
			Raccoon,
			Rat,
			Rebel,
			Reflection,
			Rhino,
			Rigger,
			Rogue,
			Sable,
			Salamander,
			Samurai,
			Sand,
			Saproling,
			Satyr,
			Scarecrow,
			Scientist,
			Scion,
			Scorpion,
			Scout,
			Serf,
			Serpent,
			Servo,
			Shade,
			Shaman,
			Shapeshifter,
			Shark,
			Sheep,
			Siren,
			Skeleton,
			Slith,
			Sliver,
			Slug,
			Snake,
			Soldier,
			Soltari,
			Spawn,
			Specter,
			Spellshaper,
			Sphinx,
			Spider,
			Spike,
			Spirit,
			Splinter,
			Sponge,
			Squid,
			Squirrel,
			Starfish,
			Surrakar,
			Survivor,
			Tentacle,
			Tetravite,
			Thalakos,
			Thopter,
			Thrull,
			Tiefling,
			Treefolk,
			Trilobite,
			Triskelavite,
			Troll,
			Turtle,
			Tyranid,
			Unicorn,
			Vampire,
			Vedalken,
			Viashino,
			Voliver,
			Wall,
			Warlock,
			Warrior,
			Weird,
			Werewolf,
			Whale,
			Wizard,
			Wolf,
			Wolverine,
			Wombat,
			Worm,
			Wraith,
			Wurm,
			Yeti,
			Zombie,
			Zubera,
			Aura,
			Background,
			Cartouche,
			Function,
			Curse,
			Rune,
			Saga,
			Shrine,
			Role,
			Desert,
			Forest,
			Gate,
			Island,
			Lair,
			Locus,
			Mine,
			Mountain,
			Plains,
			PowerPlant,
			Sphere,
			Swamp,
			Tower,
			Urzas,
			Ajani,
			Angrath,
			Arlinn,
			Ashiok,
			Basri,
			Bolas,
			Calix,
			Chandra,
			Dack,
			Dakkon,
			Davriel,
			Domri,
			Dovin,
			Elspeth,
			Estrid,
			Freyalise,
			Garruk,
			Gideon,
			Hualti,
			Jace,
			Jared,
			Jaya,
			Jeska,
			Kaito,
			Karn,
			Kasmina,
			Kaya,
			Kiora,
			Koth,
			Liliana,
			Lukka,
			Narset,
			Nahiri,
			Niko,
			Nissa,
			Obi,
			Ob,
			Oko,
			Ral,
			Rowan,
			Saheeli,
			Samut,
			Sarkhan,
			Serra,
			Sorin,
			Tamiyo,
			Teferi,
			Teyo,
			Tezzeret,
			Tibalt,
			Tyvar,
			Ugin,
			Venser,
			Vivien,
			Vraska,
			Will,
			Windgrace,
			Wrenn,
			Xenagos,
			Yanggu,
			Yanling,
			Adventure,
			Arcane,
			Lesson,
			Trap,
		], random.randint(0, 363))

		colors = random.sample([
			Black,
			Blue,
			Colorless,
			Green,
			Red,
			White,
		], random.randint(0, 6))

		return Identity(
			Supertypes(*supertypes),
			Types(*types),
			Subtypes(*subtypes),
			Colors(*colors),
		)


	# ------------------------------------------------------------------------------------------
	# ------------------------ Method :: Generate a Tensorized Identity ------------------------
	# ------------------------------------------------------------------------------------------
	@staticmethod
	def generate(autoencoder: Autoencoder) -> None:

		schematics = autoencoder.schematics
		embeddings = autoencoder.embeddings

		accumulator, null, padding = embeddings[Slot]
		print(accumulator, null, padding)

		for attribute, value in White.attributes.items():
			print(attribute, value)